### ISSUE TITLE
Stop applying topic names with parameters

### ISSUE THREAD

**Issue by kokosabu** [ros-drivers/transport_drivers#13]
Following the general consensus, stop applying topic names with parameter files and use remapping to change the topic names. For more information, please refer to [this issue](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/254) on Autoware.Auto.

See also: https://github.com/ros-drivers/transport_drivers/blob/master/udp_driver/include/udp_driver/udp_driver_node.hpp#L93

**Comment by JWhitleyWork** [comment]
Closed by #22.
