### ISSUE TITLE
switch to more standard default branch setup

### ISSUE THREAD

**Issue by flynneva** [ros-drivers/transport_drivers#26]
right now the default branch for this repo is set to `ros2`. as far as I know this repo is only meant for ROS2....so to me there might be a better name for the default branch.

I really like the standard `develop` and `main` or `master` setup, where `develop` is where active development happens & `main` or `master` has the most recent tested & released code.

what do you think?

**Comment by JWhitleyWork** [comment]
I'm fine with `main` (there's been a big push to move away from `master` lately both in ROS and GIthub in general due to the negative connotations) and `develop`.

**Comment by JWhitleyWork** [comment]
Done. And re-targetd your MR to `develop`.

**Comment by JWhitleyWork** [comment]
https://github.com/ros/rosdistro/pull/28154
