### ISSUE TITLE
udp_driver only supports one type of message

### ISSUE THREAD

**Issue by esteve** [ros-drivers/transport_drivers#3]
udp_driver only accepts one type of output, see https://github.com/ros-drivers/transport_drivers/blob/7660c2a02700ffafe8fc0839d45ff688c1a31db4/udp_driver/include/udp_driver/udp_driver_node.hpp#L40

For some sensors, it'd be useful to be able to generate messages of different types

**Comment by esteve** [comment]
@cho3 FYI

**Comment by flynneva** [comment]
@esteve with the new updates to `io_context` we can add converters for any ROS2 message type.  already we have converters for most of the `std_msgs` and also the more genereic `udp_msgs`.

do you think that is enough to close this issue?

**Comment by JWhitleyWork** [comment]
This is no longer the case since the major code reorg for 1.0. Closing.
