### ISSUE TITLE
replace MutBuffer with std::vector<uint8_t>

### ISSUE THREAD

**Issue by flynneva** [ros-drivers/transport_drivers#48]
referenced on #40 comments since #40 begins to migrate towards `std::vector<uint8_t>` to fix some race conditions. lets go ahead and replace the rest of the `MutBuffers` with `std::vector<uint8_t>` to keep it all consistent.

**Comment by reza-ebrahimi** [comment]
I read #40 comments, but I'm really didn't get the exact reason of changing MutBuffer to a vector of bytes?

**Comment by flynneva** [comment]
@reza-ebrahimi mutable buffers do not own the underlying data that they refer to. This caused us to see some threading issues where the buffers were pointing to locations in the memory that no longer had the data we wanted. I tried showing it in the print outs on #40

**Comment by flynneva** [comment]
Also there is some added benefits since we can use a vector of bytes right in 'udp_socket' as the buffer to fill - which makes it super easy to then parse out into different messages in our 'to_msg' and 'from_msg' functions

**Comment by JWhitleyWork** [comment]
Done for `serial_driver` in #47. Will create a separate MR to update `udp_driver` to match once #47 is merged.

**Comment by reza-ebrahimi** [comment]
Why we need the buffer to own the underlying data? Also you mentioned about threading issues, IMO if there are such problems, there should be a better way to fix them.

Mutable buffers are accepting both primitive and POD types with zero copy of the data. Your changes do copy of the data to vector of bytes which is very expensive operation and totally unnecessary.

**Comment by flynneva** [comment]
@reza-ebrahimi if you know of a better way to fix it please make a PR!

**Comment by flynneva** [comment]
closed with #50
