### ISSUE TITLE
Support serial break

### ISSUE THREAD

**Issue by RFRIEDM-Trimble** [ros-drivers/transport_drivers#75]
Can support be added to send a break sequence to the serial device using asio's [send_break](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/basic_serial_port/send_break.html)? 

For example, I'd like to call `SerialPort.send_break()`

My embedded device has a special sequence that relies on sending a break command. 

I am happy to do the implementation, just wanted to pass it over here before writing the PR.

**Comment by JWhitleyWork** [comment]
Certainly! I don't see why this would cause any issues. Feel free to add the PR and I'll give it a review!
