### ISSUE TITLE
SerialPort tries to close port a possible second time in destructor

### ISSUE THREAD

**Issue by sven-hoek** [ros-drivers/transport_drivers#87]
In https://github.com/ros-drivers/transport_drivers/pull/85, the port gets closed in case of an error but inside the constructor, `close()` is called a second time, which leads to errors.

**Comment by sven-hoek** [comment]
Ignore #88 , #89 is the current pull request for this issue

**Comment by JWhitleyWork** [comment]
Closed by #89.
