### ISSUE TITLE
Release new version of the drivers

### ISSUE THREAD

**Issue by esteve** [ros-drivers/transport_drivers#9]
The version of the packages available on the buildfarm is lagging behind the current version on master.

**Comment by JWhitleyAStuff** [comment]
A 0.0.4 PR has already been merged to `rosdistro` but is not yet available in the repos. The last package sync was 12/12/2019 and the PR was submitted after that so it should be sync'd soon.

**Comment by JWhitleyWork** [comment]
Sync was completed. 0.0.4 was released to Dashing.
